jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    environment:
      FOO: bar
    parallelism: 1
    resource_class: small
    working_directory: ~/pimouse_ros
    steps:
      - checkout
      - run: cd ~/pimouse_ros
      - run: sudo apt-get update
      - run: wget https://cmake.org/files/v3.6/cmake-3.6.2.tar.gz
      - run: tar xvf cmake-3.6.2.tar.gz
      - run: cd cmake-3.6.2; ./bootstrap && make && make install
      - run: sudo apt-get install -y python-pip
      - run: sudo apt-get install -y rsync
      - run: bash -xve ./test/travis_ros_install.bash
      - run: source ~/catkin_ws/devel/setup.bash
      - run: bash -xve ./test/travis_package_make.bash
      - run: source ~/catkin_ws/devel/setup.bash 
      - run: bash -xve ./test/travis_prepare_dummy_files.bash
      - run: source ~/catkin_ws/devel/setup.bash; rostest pimouse_ros test.launch
